
(6, 7)
Starting Iteration
Epoch 1/10
25/25 [==============================] - 3s 18ms/step - loss: 2.9485 - pi_loss: 1.9852 - v_loss: 0.9633
Epoch 2/10
25/25 [==============================] - 0s 12ms/step - loss: 2.7177 - pi_loss: 1.9394 - v_loss: 0.7783
Epoch 3/10
25/25 [==============================] - 0s 12ms/step - loss: 2.5930 - pi_loss: 1.9314 - v_loss: 0.6617
Epoch 4/10
25/25 [==============================] - 0s 13ms/step - loss: 2.4543 - pi_loss: 1.9228 - v_loss: 0.5315
Epoch 5/10
25/25 [==============================] - 0s 12ms/step - loss: 2.3910 - pi_loss: 1.9160 - v_loss: 0.4750
Epoch 6/10
25/25 [==============================] - 0s 14ms/step - loss: 2.4081 - pi_loss: 1.9103 - v_loss: 0.4978
Epoch 7/10
25/25 [==============================] - 0s 14ms/step - loss: 2.2981 - pi_loss: 1.9029 - v_loss: 0.3952
Epoch 8/10
25/25 [==============================] - 0s 12ms/step - loss: 2.2596 - pi_loss: 1.8929 - v_loss: 0.3667
Epoch 9/10
25/25 [==============================] - 0s 15ms/step - loss: 2.2356 - pi_loss: 1.8888 - v_loss: 0.3468
Epoch 10/10
25/25 [==============================] - 0s 13ms/step - loss: 2.1870 - pi_loss: 1.8806 - v_loss: 0.3064
Loading Model
Comparing Networks
Candidate: 14 Current: 25
player 1 wins, retaining old network
WARNING:absl:Found untraced functions such as conv2d_1_layer_call_fn, conv2d_1_layer_call_and_return_conditional_losses, re_lu_1_layer_call_fn, re_lu_1_layer_call_and_return_conditional_losses, conv2d_2_layer_call_fn while saving (showing 5 of 60). These functions will not be directly callable after loading.
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    coach.train()
  File "C:\Users\carlos\Desktop\cs\alpha-zero-c4\coach.py", line 75, in train
    random_arena.pit()
  File "C:\Users\carlos\Desktop\cs\alpha-zero-c4\arena.py", line 47, in pit
    self.battle(verbose)
  File "C:\Users\carlos\Desktop\cs\alpha-zero-c4\arena.py", line 32, in battle
    game.get_next_state(1,action)
  File "C:\Users\carlos\Desktop\cs\alpha-zero-c4\connect4\game.py", line 24, in get_next_state
    return self.board.take_action(player,action)
  File "C:\Users\carlos\Desktop\cs\alpha-zero-c4\connect4\board.py", line 22, in take_action
    row = get_row(self.pieces,column)
  File "C:\Users\carlos\Desktop\cs\alpha-zero-c4\connect4\logic.py", line 8, in get_row
    if pieces[i][column] == 0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()